services:
  pa_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pa_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_BASE=http://127.0.0.1:5000
      - API_BASE=http://192.168.1.223:5000
    # networks:
    #   - pa-net

# networks:
#   pa-net:
#     external: true